import { NeighbourhoodItem, OnlineStoreItem, BorrowRequest, LendItem } from '@/types';
import { validateAndCleanListings } from './format';
import { EXTENDED_ONLINE_ITEMS } from './onlineCatalog';

const RAW_NEIGHBOURHOOD_ITEMS: NeighbourhoodItem[] = [
  {
    id: 'n-1',
    name: 'DeWalt Cordless Power Drill Set',
    category: 'Tools',
    distanceKm: 0.4,
    pricePerDay: 400,
    pricePerHour: 100,
    marketPrice: 28000,
    securityDeposit: 3000,
    availabilityStatus: 'Available',
    ownerName: 'Sarah M.',
    ownerRating: 4.9,
    timesBorrowed: 14,
    iconName: 'Wrench',
    description: '18V cordless drill with 2 battery packs and a 30-piece drill bit set. Perfect for home projects.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-2',
    name: 'Bosch High-Pressure Washer',
    category: 'Tools',
    distanceKm: 1.2,
    pricePerDay: 750,
    pricePerHour: 180,
    marketPrice: 35000,
    securityDeposit: 4000,
    availabilityStatus: 'Available',
    ownerName: 'David K.',
    ownerRating: 4.8,
    timesBorrowed: 9,
    iconName: 'Sparkles',
    description: '140 bar electric pressure washer with foam nozzle. Great for patio and vehicle cleaning.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-3',
    name: 'Le Creuset Dutch Oven (5.5 Qt)',
    category: 'Cookware',
    distanceKm: 0.7,
    pricePerDay: 350,
    pricePerHour: 80,
    marketPrice: 32000,
    securityDeposit: 3500,
    availabilityStatus: 'Available',
    ownerName: 'Elena R.',
    ownerRating: 5.0,
    timesBorrowed: 22,
    iconName: 'Utensils',
    description: 'Enameled cast iron Dutch oven in Cerise Red. Excellent heat retention for slow cooking and sourdough baking.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-4',
    name: 'Epson 1080p Portable Projector',
    category: 'Electronics',
    distanceKm: 2.1,
    pricePerDay: 900,
    pricePerHour: 200,
    marketPrice: 55000,
    securityDeposit: 6000,
    availabilityStatus: 'Available',
    ownerName: 'Marcus T.',
    ownerRating: 4.7,
    timesBorrowed: 18,
    iconName: 'Tv',
    description: 'Compact Full HD projector with HDMI and built-in speaker. Comes with portable 80-inch folding screen.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1574267432553-4b4628081c31?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-5',
    name: 'Thule 3-Bike Rear Hitch Rack',
    category: 'Sports',
    distanceKm: 1.8,
    pricePerDay: 500,
    pricePerHour: 120,
    marketPrice: 25000,
    securityDeposit: 3000,
    availabilityStatus: 'Available',
    ownerName: 'Alex B.',
    ownerRating: 4.9,
    timesBorrowed: 11,
    iconName: 'Bike',
    description: 'Sturdy bike rack fits 2-inch receiver. Locks included. Folds down for easy trunk access.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-6',
    name: 'Stand-Up Paddleboard (Inflatable)',
    category: 'Outdoors',
    distanceKm: 3.4,
    pricePerDay: 850,
    pricePerHour: 200,
    marketPrice: 45000,
    securityDeposit: 5000,
    availabilityStatus: 'Available',
    ownerName: 'Priya N.',
    ownerRating: 4.8,
    timesBorrowed: 7,
    iconName: 'Waves',
    description: '10ft6in paddleboard package including high-pressure dual pump, collapsible paddle, and travel bag.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-7',
    name: 'MacBook Pro M2 16-inch Laptop',
    category: 'Electronics',
    distanceKm: 0.5,
    pricePerDay: 1400,
    pricePerHour: 300,
    marketPrice: 190000,
    securityDeposit: 18000,
    availabilityStatus: 'Available',
    ownerName: 'Sarah M.',
    ownerRating: 4.9,
    timesBorrowed: 18,
    iconName: 'Tv',
    description: 'Apple M2 Pro chip with 16-core GPU, 16GB RAM, 512GB SSD. Pristine condition with charger and protective case. Great for software development and video editing.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-8',
    name: 'Canon EOS R6 Full-Frame DSLR Camera Kit',
    category: 'Cameras',
    distanceKm: 0.8,
    pricePerDay: 1600,
    pricePerHour: 350,
    marketPrice: 210000,
    securityDeposit: 20000,
    availabilityStatus: 'Available',
    ownerName: 'David K.',
    ownerRating: 5.0,
    timesBorrowed: 26,
    iconName: 'Camera',
    description: 'Includes RF 24-105mm F4 L IS USM lens, 64GB Extreme Pro SD card, 2 batteries, and camera bag. Incredible 4K 60p video and in-body stabilization.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-9',
    name: 'Dune & Sci-Fi Masterworks Box Set (6 Volumes)',
    category: 'Books',
    distanceKm: 0.3,
    pricePerDay: 150,
    pricePerHour: 30,
    marketPrice: 5000,
    securityDeposit: 500,
    availabilityStatus: 'Available',
    ownerName: 'Elena R.',
    ownerRating: 4.8,
    timesBorrowed: 15,
    iconName: 'BookOpen',
    description: 'Complete Frank Herbert Dune collection in deluxe hardcover binding. Spotless condition, great for weekend reading or sci-fi enthusiasts.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-10',
    name: 'Trek X-Caliber 8 Mountain Bicycle (29er)',
    category: 'Vehicles',
    distanceKm: 1.2,
    pricePerDay: 650,
    pricePerHour: 150,
    marketPrice: 85000,
    securityDeposit: 5000,
    availabilityStatus: 'Available',
    ownerName: 'Alex B.',
    ownerRating: 4.9,
    timesBorrowed: 32,
    iconName: 'Bike',
    description: 'Lightweight aluminum frame, RockShox air fork, Shimano 1x12 drivetrain, and hydraulic disc brakes. Freshly serviced, helmet and heavy-duty lock included.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-11',
    name: 'Sony PlayStation 5 Disc Console + 2 Controllers',
    category: 'Electronics',
    distanceKm: 0.9,
    pricePerDay: 950,
    pricePerHour: 200,
    marketPrice: 55000,
    securityDeposit: 7000,
    availabilityStatus: 'Available',
    ownerName: 'Rohan S.',
    ownerRating: 4.9,
    timesBorrowed: 42,
    iconName: 'Tv',
    description: 'Ultra-high speed SSD, 4K HDR 120Hz support. Loaded with EA FC 24, Spider-Man 2, and Mortal Kombat 1. Includes 2 wireless controllers and HDMI 2.1 cable.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800']
  },
  {
    id: 'n-12',
    name: 'Herman Miller Aeron Ergonomic Office Chair (Size B)',
    category: 'Furniture',
    distanceKm: 2.0,
    pricePerDay: 700,
    pricePerHour: 150,
    marketPrice: 110000,
    securityDeposit: 12000,
    availabilityStatus: 'Available',
    ownerName: 'Neha P.',
    ownerRating: 5.0,
    timesBorrowed: 14,
    iconName: 'Store',
    description: 'Fully adjustable PostureFit SL lumbar support, 3D armrests, and breathable Pellicle mesh. Ideal for home office testing or temporary work-from-home setups.',
    availableToNeighbours: true,
    imageUrl: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800']
  }
];

export const INITIAL_NEIGHBOURHOOD_ITEMS: NeighbourhoodItem[] = validateAndCleanListings(RAW_NEIGHBOURHOOD_ITEMS);

const RAW_ONLINE_STORE_ITEMS: OnlineStoreItem[] = [
  {
    id: 'item-online-1',
    name: 'Sony FX3 Cinema Line Full-Frame Camera Kit',
    category: 'Cameras',
    brand: 'Sony',
    platformName: 'RentMyGear Certified Partner',
    pricePerHour: 350,
    pricePerDay: 2400,
    pricePerWeek: 12000,
    marketPrice: 399000,
    depositAmount: 25000,
    timesRented: 184,
    timesBorrowed: 184,
    iconName: 'Camera',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.9,
    reviewCount: 38,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Like New (Sanitized & Calibration Checked)',
    description: 'Professional Full-Frame Cinema Line Camera featuring 4K 120p recording, S-Cinetone color profile, 15+ stops dynamic range, dual CFexpress Type A slots, and included XLR handle unit for high-end video productions.',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1520549233664-03f65c1d1327?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      '4K Full-Frame 10.2MP Back-Illuminated Exmor R CMOS Sensor',
      '15+ Stops Dynamic Range with S-Cinetone Color Science',
      'Dual Native ISO (800 / 12800) for Ultra Low Light Clarity',
      'Top XLR Handle with 2x Full XLR Audio Inputs',
      'Includes 2x NP-FZ100 Batteries + Dual Charger & Hardcase'
    ],
    specifications: {
      'Sensor Type': '35mm Full-Frame (35.6 x 23.8mm)',
      'Mount Type': 'Sony E-Mount',
      'Video Resolution': '4K QFHD (3840 x 2160) up to 120fps',
      'Media Format': 'CFexpress Type A / SDXC UHS-II',
      'Weight': '715g (Body with Battery & Memory Card)'
    },
    cancellationPolicy: 'Free cancellation up to 24 hours before your start date. 50% refund thereafter.',
    damagePolicy: 'Insured against accidental liquid or drop damage up to ₹50,000 with optional ₹199 Waiver.',
    latePenaltyFee: '₹450/hour or ₹3,000/day for overdue unreturned items.',
    reviews: [
      {
        id: 'rev-1',
        userName: 'Rohan Sharma',
        rating: 5,
        date: '2 days ago',
        comment: 'Rented for a music video shoot over the weekend. Sensor was spotless, batteries were fully charged, and delivery arrived 2 hours early!',
        verifiedRenter: true,
        helpfulCount: 14
      },
      {
        id: 'rev-2',
        userName: 'Ananya Verma',
        rating: 5,
        date: '1 week ago',
        comment: 'Super easy rental workflow. The deposit was refunded back to my UPI account within 4 hours after pickup inspection.',
        verifiedRenter: true,
        helpfulCount: 9
      }
    ]
  },
  {
    id: 'item-online-2',
    name: 'Sony PlayStation 5 Disc Console + 2 DualSense Controllers',
    category: 'Electronics',
    brand: 'Sony',
    platformName: 'GamerRent Hub',
    pricePerHour: 150,
    pricePerDay: 950,
    pricePerWeek: 4500,
    marketPrice: 54990,
    depositAmount: 8000,
    timesRented: 312,
    timesBorrowed: 312,
    iconName: 'Gamepad2',
    deliveryEstimate: 'Express 4-Hour Delivery',
    rating: 4.8,
    reviewCount: 64,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent (Pre-installed Games)',
    description: 'Experience ultra-fast loading with a high-speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio. Comes loaded with FIFA 24, Spider-Man 2, and God of War Ragnarök.',
    imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      'Custom Ultra-High Speed 825GB NVMe SSD',
      'Ray Tracing & 4K 120Hz Output Support',
      '2x DualSense Wireless Controllers (Cosmic Red & White)',
      'Pre-installed Top Multiplayer Games',
      'HDMI 2.1 Cable + Power Cord Included'
    ],
    specifications: {
      'Storage': '825GB High-Speed SSD',
      'Resolution': 'Up to 4K 120Hz / 8K Output',
      'Optical Drive': '4K UHD Blu-ray Disc Drive',
      'Weight': '4.5 kg'
    },
    cancellationPolicy: 'Free cancellation up to 12 hours prior to dispatch.',
    damagePolicy: 'Standard deposit covers cosmetic scratches. Major component failure replaced free.',
    latePenaltyFee: '₹200/hour late fee.',
    reviews: [
      {
        id: 'rev-3',
        userName: 'Vikramaditya S.',
        rating: 5,
        date: '3 days ago',
        comment: 'Hosted a gaming night with friends. Delivery was super quick, controllers were sanitized, and games played flawlessly.',
        verifiedRenter: true,
        helpfulCount: 21
      }
    ]
  },
  {
    id: 'item-online-3',
    name: 'JBL PartyBox 310 Portable Wireless Bluetooth Party Speaker',
    category: 'Party',
    brand: 'JBL',
    platformName: 'PartyRentals Partner',
    pricePerHour: 200,
    pricePerDay: 1200,
    pricePerWeek: 5500,
    marketPrice: 42999,
    depositAmount: 7500,
    timesRented: 245,
    timesBorrowed: 245,
    iconName: 'Radio',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.9,
    reviewCount: 52,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Great Sound Quality (Inspected)',
    description: '240 Watts of powerful JBL Pro Sound with synced dynamic RGB light show, 18-hour rechargeable battery life, smooth-glide wheels, and dual mic/guitar inputs for karaoke nights.',
    imageUrl: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      '240W RMS JBL Signature Sound with Bass Boost',
      'Dynamic RGB Lightshow Synced to Beat',
      'Up to 18 Hours Battery Playtime',
      'IPX4 Splashproof Rating for Outdoor Events',
      'Includes 1x Shure Wireless Vocal Microphone'
    ],
    specifications: {
      'Power Output': '240 Watts RMS',
      'Battery Life': 'Up to 18 Hours',
      'Connectivity': 'Bluetooth 5.1, USB, AUX, Mic/Guitar In',
      'Weight': '17.4 kg (Telescopic Handle & Wheels)'
    },
    cancellationPolicy: 'Free cancellation until 6 hours before event time.',
    damagePolicy: 'Weatherproof enclosure included. Deposit covers mechanical driver damage.',
    latePenaltyFee: '₹250/hour late fee.',
    reviews: [
      {
        id: 'rev-4',
        userName: 'Sneha Patel',
        rating: 5,
        date: '5 days ago',
        comment: 'Amazing bass! Made our terrace party legendary. Battery easily lasted 10 hours on high volume.',
        verifiedRenter: true,
        helpfulCount: 18
      }
    ]
  },
  {
    id: 'item-online-4',
    name: 'Quechua 4-Person Waterproof All-Weather Camping Tent Package',
    category: 'Outdoors',
    brand: 'Decathlon Quechua',
    platformName: 'OutdoorGear Express',
    pricePerHour: 100,
    pricePerDay: 650,
    pricePerWeek: 2800,
    marketPrice: 14999,
    depositAmount: 3000,
    timesRented: 410,
    timesBorrowed: 410,
    iconName: 'Tent',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.8,
    reviewCount: 78,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Clean & Waterproof Tested',
    description: 'Spacious 4-person dome tent featuring Fresh & Black thermal technology to block 99% of daylight and keep tent cool. Includes 4x thermal sleeping bags and 2x inflatable sleeping pads.',
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      'Fresh & Black Patented Daylight Block Technology',
      'Tropical Rain & 50 km/h Wind Tunnel Tested',
      'Includes 4x Sub-Zero Rated Sleeping Bags',
      'Includes High-Pressure Foot Pump & Ground Tarp',
      'Compact Carry Duffel Bag (Weight: 6.8kg)'
    ],
    specifications: {
      'Capacity': '4 Persons (240 x 210cm Bedroom)',
      'Waterproofing': '2000 mm/h/m² Tropical Rain Test',
      'Setup Time': '10 Minutes (Color-Coded Poles)'
    },
    cancellationPolicy: 'Free cancellation up to 48 hours before trip date.',
    damagePolicy: 'Small seam tears covered by partner maintenance guarantee.',
    latePenaltyFee: '₹150/hour late fee.',
    reviews: [
      {
        id: 'rev-5',
        userName: 'Karthik Raja',
        rating: 5,
        date: '1 week ago',
        comment: 'Took this tent to Pawna Lake camp. Fresh & Black tech really keeps the interior pitch dark in the morning sun!',
        verifiedRenter: true,
        helpfulCount: 30
      }
    ]
  },
  {
    id: 'item-online-5',
    name: 'Bosch Professional Heavy-Duty Power Tool & Drill Kit',
    category: 'Tools',
    brand: 'Bosch',
    platformName: 'ToolShare Pro Partner',
    pricePerHour: 80,
    pricePerDay: 500,
    pricePerWeek: 2200,
    marketPrice: 18500,
    depositAmount: 3500,
    timesRented: 165,
    timesBorrowed: 165,
    iconName: 'Wrench',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.7,
    reviewCount: 29,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Fully Calibrated & Cleaned',
    description: 'Industrial-grade 18V Brushless Impact Driver and Rotary Hammer Drill kit with 50-piece masonry, wood, and metal drill bit set. Perfect for heavy wall mounting and renovation work.',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      'Brushless EC Motor with 180 Nm Torque',
      '2x 4.0Ah CoolPack Lithium-Ion Batteries',
      'Includes Heavy Duty Masonry & Steel Bit Set',
      'Ergonomic Vibration Control Handle',
      'L-BOXX Hard Carrying Case Included'
    ],
    specifications: {
      'Torque Max': '180 Nm',
      'No-Load Speed': '0-2800 RPM',
      'Chuck Diameter': '13mm Keyless All-Metal'
    },
    cancellationPolicy: 'Free cancellation until item dispatch.',
    damagePolicy: 'Normal bit wear and tear is expected. Deposit applies to lost components.',
    latePenaltyFee: '₹100/hour late fee.',
    reviews: [
      {
        id: 'rev-6',
        userName: 'Amitabh Sen',
        rating: 5,
        date: '2 weeks ago',
        comment: 'Mounted 6 wall shelves and a 65-inch TV without hassle. Batteries lasted the entire day.',
        verifiedRenter: true,
        helpfulCount: 12
      }
    ]
  },
  {
    id: 'item-online-6',
    name: 'Bowflex SelectTech 552 Adjustable Dumbbells Set (2x 24kg)',
    category: 'Fitness',
    brand: 'Bowflex',
    platformName: 'FitRent Direct',
    pricePerHour: 90,
    pricePerDay: 550,
    pricePerWeek: 2400,
    marketPrice: 38000,
    depositAmount: 6000,
    timesRented: 198,
    timesBorrowed: 198,
    iconName: 'Store',
    deliveryEstimate: 'Doorstep Delivery in 24h',
    rating: 4.9,
    reviewCount: 44,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent (Includes Floor Stand)',
    description: 'Replaces 15 sets of weights. Adjusts from 2 to 24 kg in 1.5 kg increments with a turn of a dial. Includes heavy-duty ergonomic floor stand and rubber exercise mat.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800',
    imageUrls: [
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800'
    ],
    features: [
      'Adjustable Dial System from 2kg to 24kg per Dumbbell',
      'Replaces 30 Individual Dumbbells in Minimal Space',
      'Durable Molding Around Metal Plates for Smooth Lift',
      'Includes Bowflex Heavy Duty Dumbbell Stand',
      'Complimentary Rubber Gym Floor Protection Mat'
    ],
    specifications: {
      'Weight Range': '2 to 24 kg per dumbbell',
      'Weight Settings': '15 Incremental Settings',
      'Dimensions': '40 x 20 x 23 cm'
    },
    cancellationPolicy: 'Free cancellation up to 24h before delivery.',
    damagePolicy: 'Covers dial mechanism maintenance.',
    latePenaltyFee: '₹120/hour late fee.',
    reviews: [
      {
        id: 'rev-7',
        userName: 'Deepak V.',
        rating: 5,
        date: '4 days ago',
        comment: 'Rented for a month-long workout challenge. The dial selection mechanism works super smoothly.',
        verifiedRenter: true,
        helpfulCount: 16
      }
    ]
  },
  {
    id: 'item-online-7',
    name: 'Professional Claw Hammer (16 oz)',
    category: 'Tools',
    brand: 'Stanley',
    platformName: 'ToolShare Pro',
    pricePerHour: 10,
    pricePerDay: 50,
    pricePerWeek: 250,
    marketPrice: 800,
    depositAmount: 200,
    timesRented: 50,
    timesBorrowed: 50,
    iconName: 'Wrench',
    deliveryEstimate: 'Next-Day Delivery',
    rating: 4.8,
    reviewCount: 22,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent',
    description: 'Heavy duty steel claw hammer with shock-absorbing grip. Ideal for carpentry, framing, and general household repairs.',
    imageUrl: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&q=80&w=800'],
    features: ['16 oz Head Weight', 'Forged Steel Construction', 'Anti-vibration Grip'],
    specifications: { 'Material': 'Steel', 'Weight': '450g' },
    cancellationPolicy: 'Free cancellation up to 12 hours prior to dispatch.',
    damagePolicy: 'Covered under normal wear and tear.',
    latePenaltyFee: '₹10/hour',
    reviews: []
  },
  {
    id: 'item-online-8',
    name: 'Electric Tool Kit - 100 Pieces',
    category: 'Tools',
    brand: 'Bosch',
    platformName: 'ToolShare Pro',
    pricePerHour: 50,
    pricePerDay: 250,
    pricePerWeek: 1200,
    marketPrice: 5000,
    depositAmount: 1000,
    timesRented: 120,
    timesBorrowed: 120,
    iconName: 'Wrench',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.9,
    reviewCount: 45,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Like New',
    description: 'Complete home toolkit including pliers, screwdrivers, wrenches, hammer, measuring tape, and electric tester in a compact carry case.',
    imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&q=80&w=800'],
    features: ['100 Essential Tools', 'Durable Molded Case', 'Rust-Resistant Finish'],
    specifications: { 'Case Material': 'Plastic', 'Total Weight': '2.5kg' },
    cancellationPolicy: 'Free cancellation up to 12 hours prior to dispatch.',
    damagePolicy: 'Lost tools must be reimbursed from deposit.',
    latePenaltyFee: '₹50/day',
    reviews: []
  },
  {
    id: 'item-online-9',
    name: 'Babolat Pure Drive Tennis Kit (2 Rackets + Balls)',
    category: 'Sports',
    brand: 'Babolat',
    platformName: 'SportsRent',
    pricePerHour: 40,
    pricePerDay: 200,
    pricePerWeek: 1000,
    marketPrice: 20000,
    depositAmount: 4000,
    timesRented: 65,
    timesBorrowed: 65,
    iconName: 'Sparkles',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.9,
    reviewCount: 15,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent',
    description: 'Two professional grade Babolat Pure Drive tennis rackets with a fresh can of 3 Wilson tennis balls and a protective carry bag.',
    imageUrl: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&q=80&w=800'],
    features: ['2x Professional Rackets', 'Includes 3 New Balls', 'Carry Bag'],
    specifications: { 'Head Size': '100 sq in', 'Weight': '300g' },
    cancellationPolicy: 'Free cancellation anytime.',
    damagePolicy: 'Broken strings covered. Frame cracks from abuse charged from deposit.',
    latePenaltyFee: '₹50/day',
    reviews: []
  },
  {
    id: 'item-online-10',
    name: 'Yonex Badminton Kit (4 Rackets + Shuttlecocks + Net)',
    category: 'Sports',
    brand: 'Yonex',
    platformName: 'SportsRent',
    pricePerHour: 30,
    pricePerDay: 150,
    pricePerWeek: 700,
    marketPrice: 6000,
    depositAmount: 1500,
    timesRented: 85,
    timesBorrowed: 85,
    iconName: 'Sparkles',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.7,
    reviewCount: 30,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Great',
    description: 'Perfect for family outings. Includes 4 Yonex graphite rackets, a tube of Mavis 350 nylon shuttlecocks, and a portable folding net.',
    imageUrl: 'https://images.unsplash.com/photo-1622599511051-16f55a1234d0?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1622599511051-16f55a1234d0?auto=format&fit=crop&q=80&w=800'],
    features: ['4 Graphite Rackets', 'Portable Net Included', 'Nylon Shuttlecocks'],
    specifications: { 'Racket Material': 'Graphite', 'Net Width': '3 meters' },
    cancellationPolicy: 'Free cancellation anytime.',
    damagePolicy: 'Frame damages charged from deposit.',
    latePenaltyFee: '₹30/day',
    reviews: []
  },
  {
    id: 'item-online-11',
    name: 'Premium English Ash Wood Carrom Board (35 Inch)',
    category: 'Party',
    brand: 'Precise',
    platformName: 'BoardGame Hub',
    pricePerHour: 20,
    pricePerDay: 150,
    pricePerWeek: 600,
    marketPrice: 4500,
    depositAmount: 1000,
    timesRented: 40,
    timesBorrowed: 40,
    iconName: 'Gamepad2',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.8,
    reviewCount: 12,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Like New (Super Smooth)',
    description: 'Tournament quality 35-inch carrom board with English Ash wood frame and 8mm thick waterproof birch plywood. Comes with coins, striker, and powder.',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&q=80&w=800'],
    features: ['8mm Waterproof Birch Ply', 'Tournament Coins & Striker', 'Carrom Powder Included'],
    specifications: { 'Size': '35 x 35 inches', 'Playing Surface': '29 x 29 inches' },
    cancellationPolicy: 'Free cancellation up to 6 hours before dispatch.',
    damagePolicy: 'Water damage or deep scratches charged from deposit.',
    latePenaltyFee: '₹40/day',
    reviews: []
  },
  {
    id: 'item-online-12',
    name: 'Complete Birthday Party Decoration Kit',
    category: 'Party',
    brand: 'PartyPro',
    platformName: 'PartyRentals Partner',
    pricePerHour: 30,
    pricePerDay: 200,
    pricePerWeek: 500,
    marketPrice: 3000,
    depositAmount: 0,
    timesRented: 210,
    timesBorrowed: 210,
    iconName: 'Gift',
    deliveryEstimate: 'Express 4-Hour Delivery',
    rating: 4.6,
    reviewCount: 56,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent',
    description: 'Reusable happy birthday neon sign, 2 metallic fringe curtains, balloon pump (balloons not included), fairy lights, and photo booth props.',
    imageUrl: 'https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&q=80&w=800'],
    features: ['Neon Happy Birthday Sign', 'Fairy Lights', 'Balloon Electric Pump'],
    specifications: { 'Sign Power': 'USB/Adapter', 'Curtain Size': '3x6 ft' },
    cancellationPolicy: 'Free cancellation up to 2 hours before delivery.',
    damagePolicy: 'Broken neon sign charged ₹1500.',
    latePenaltyFee: '₹50/day',
    reviews: []
  },
  {
    id: 'item-online-13',
    name: 'Coleman Sundome 6-Person Camping Tent',
    category: 'Outdoors',
    brand: 'Coleman',
    platformName: 'OutdoorGear Express',
    pricePerHour: 40,
    pricePerDay: 350,
    pricePerWeek: 1500,
    marketPrice: 12000,
    depositAmount: 2000,
    timesRented: 320,
    timesBorrowed: 320,
    iconName: 'Tent',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.8,
    reviewCount: 92,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Clean & Weather-Resistant',
    description: 'Spacious 6-person dome tent. Sets up in 10 minutes. WeatherTec system with patented welded floors and inverted seams to keep you dry.',
    imageUrl: 'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?auto=format&fit=crop&q=80&w=800'],
    features: ['WeatherTec System', 'Large Windows for Ventilation', 'E-Port for Electrical Power'],
    specifications: { 'Capacity': '6 Persons', 'Center Height': '6 ft' },
    cancellationPolicy: 'Free cancellation up to 24 hours before delivery.',
    damagePolicy: 'Small tears covered. Missing poles charged from deposit.',
    latePenaltyFee: '₹100/day',
    reviews: []
  },
  {
    id: 'item-online-14',
    name: 'American Tourister 3-Piece Luggage Set (Hard Shell)',
    category: 'Outdoors',
    brand: 'American Tourister',
    platformName: 'TravelEase Rentals',
    pricePerHour: 30,
    pricePerDay: 250,
    pricePerWeek: 1100,
    marketPrice: 15000,
    depositAmount: 2500,
    timesRented: 140,
    timesBorrowed: 140,
    iconName: 'Compass',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.9,
    reviewCount: 41,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent (Sanitized)',
    description: 'Set of 3 hard shell spinner suitcases (Cabin, Medium, Large). Scratch-resistant texture, TSA combination lock, and smooth 360-degree wheels.',
    imageUrl: 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1516216628859-9bccecab13ca?auto=format&fit=crop&q=80&w=800'],
    features: ['3 Sizes (20", 24", 28")', 'TSA Approved Locks', '8 Spinner Wheels'],
    specifications: { 'Material': 'Polycarbonate', 'Total Weight': '10 kg' },
    cancellationPolicy: 'Free cancellation up to 24 hours before dispatch.',
    damagePolicy: 'Minor scratches accepted. Cracks or broken wheels charged.',
    latePenaltyFee: '₹100/day',
    reviews: []
  },
  {
    id: 'item-online-15',
    name: 'Set of 10 Premium Folding Banquet Chairs',
    category: 'Party',
    brand: 'Lifetime',
    platformName: 'PartyRentals Partner',
    pricePerHour: 40,
    pricePerDay: 400,
    pricePerWeek: 1500,
    marketPrice: 20000,
    depositAmount: 3000,
    timesRented: 95,
    timesBorrowed: 95,
    iconName: 'Store',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.7,
    reviewCount: 18,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Good',
    description: 'Set of 10 commercial-grade folding chairs. High-impact polyethylene seat and back with steel frame. Perfect for home gatherings and events.',
    imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=800'],
    features: ['Commercial Grade', 'Supports up to 200kg', 'Stain Resistant'],
    specifications: { 'Material': 'Steel & HDPE', 'Weight': '5kg per chair' },
    cancellationPolicy: 'Free cancellation up to 12 hours before delivery.',
    damagePolicy: 'Bent frames charged from deposit.',
    latePenaltyFee: '₹150/day',
    reviews: []
  },
  {
    id: 'item-online-16',
    name: 'Philips Air Fryer XXL with Smart Sensing',
    category: 'Cookware',
    brand: 'Philips',
    platformName: 'KitchenPro Rentals',
    pricePerHour: 20,
    pricePerDay: 180,
    pricePerWeek: 800,
    marketPrice: 14000,
    depositAmount: 2000,
    timesRented: 112,
    timesBorrowed: 112,
    iconName: 'Sparkles',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.8,
    reviewCount: 35,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Immaculately Cleaned & Sanitized',
    description: 'Large capacity Air Fryer XXL for roasting, baking, and frying with 90% less fat. Smart sensing technology automatically adjusts time and temperature.',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=800'],
    features: ['Smart Sensing Tech', 'Fat Removal Technology', '1.4kg Capacity'],
    specifications: { 'Power': '2225 W', 'Capacity': '7.3 L / 1.4 kg' },
    cancellationPolicy: 'Free cancellation up to 6 hours before dispatch.',
    damagePolicy: 'Burn damage or deep scratches on non-stick pan charged.',
    latePenaltyFee: '₹50/day',
    reviews: []
  },
  {
    id: 'item-online-17',
    name: 'Harry Potter Complete Box Set (Books 1-7)',
    category: 'Books',
    brand: 'Scholastic',
    platformName: 'BookShare Partner',
    pricePerHour: 5,
    pricePerDay: 20,
    pricePerWeek: 100,
    marketPrice: 3500,
    depositAmount: 500,
    timesRented: 305,
    timesBorrowed: 305,
    iconName: 'Compass',
    deliveryEstimate: 'Next-Day Shipping',
    rating: 4.9,
    reviewCount: 88,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Excellent',
    description: 'The complete set of J.K. Rowling\'s Harry Potter series. Paperback editions in excellent reading condition.',
    imageUrl: 'https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1626618012641-bfbca5a31239?auto=format&fit=crop&q=80&w=800'],
    features: ['All 7 Books', 'Collector Box', 'Paperback'],
    specifications: { 'Language': 'English', 'Format': 'Paperback' },
    cancellationPolicy: 'Free cancellation anytime.',
    damagePolicy: 'Torn pages or water damage charged from deposit.',
    latePenaltyFee: '₹5/day',
    reviews: []
  },
  {
    id: 'item-online-18',
    name: 'UPSC Complete Study Material (Prelims & Mains)',
    category: 'Books',
    brand: 'Vision IAS / Standard Authors',
    platformName: 'BookShare Partner',
    pricePerHour: 10,
    pricePerDay: 50,
    pricePerWeek: 300,
    marketPrice: 8000,
    depositAmount: 1500,
    timesRented: 45,
    timesBorrowed: 45,
    iconName: 'Compass',
    deliveryEstimate: 'Delivered in 24h',
    rating: 4.7,
    reviewCount: 14,
    ownerVerified: true,
    availableToShip: true,
    pickupAvailable: true,
    condition: 'Good (Minor Highlighting)',
    description: 'Comprehensive set of UPSC standard books including Laxmikanth, Spectrum, GC Leong, and latest Vision IAS study materials.',
    imageUrl: 'https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&q=80&w=800',
    imageUrls: ['https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&q=80&w=800'],
    features: ['15+ Standard Textbooks', 'Latest Edition', 'Previous Year Questions'],
    specifications: { 'Language': 'English', 'Weight': '15kg' },
    cancellationPolicy: 'Free cancellation anytime.',
    damagePolicy: 'Covered under normal wear. Missing books charged.',
    latePenaltyFee: '₹10/day',
    reviews: []
  }
];

export const INITIAL_ONLINE_STORE_ITEMS: OnlineStoreItem[] = validateAndCleanListings([
  ...RAW_ONLINE_STORE_ITEMS,
  ...EXTENDED_ONLINE_ITEMS,
]);

export const INITIAL_BORROW_REQUESTS: BorrowRequest[] = [
  {
    id: 'br-101',
    itemId: 'n-1',
    itemName: 'DeWalt Cordless Power Drill Set',
    lenderName: 'Sarah M.',
    borrowerName: 'You',
    price: '₹400/day',
    status: 'Picked up',
    requestedAt: '2 days ago',
  },
  {
    id: 'br-102',
    itemId: 'n-3',
    itemName: 'Le Creuset Dutch Oven (5.5 Qt)',
    lenderName: 'Elena R.',
    borrowerName: 'You',
    price: '₹350/day',
    status: 'Accepted',
    requestedAt: 'Yesterday',
  },
  {
    id: 'br-103',
    itemId: 'item-online-1',
    itemName: 'Sony FX3 Cinema Line Full-Frame Camera Kit',
    lenderName: 'RentMyGear Certified Partner',
    borrowerName: 'You',
    price: '₹2,400/day',
    status: 'Requested',
    requestedAt: '3 hours ago',
    isOnlineRental: true,
  },
];

export const INITIAL_LEND_ITEMS: LendItem[] = [
  {
    id: 'li-201',
    itemId: 'custom-1',
    itemName: 'Stihl Gas Lawn Edger',
    borrowerName: 'Carlos D. (0.3 km away)',
    price: '₹600/day',
    status: 'Requested',
    requestedAt: '1 hour ago',
  },
  {
    id: 'li-202',
    itemId: 'custom-2',
    itemName: 'Camping Folding Table & Chairs',
    borrowerName: 'Maya P. (1.1 km away)',
    price: '₹350/day',
    status: 'Accepted',
    requestedAt: '5 hours ago',
  },
];
